name: Nextflow FastQC Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v1
      
      - name: Run pipeline with test data
        run: |
          nextflow run main.nf -profile docker
      
      - name: Verify output
        run: |
          if [ ! -f "results/fastqc/sample1_fastqc.html" ]; then
            echo "FastQC HTML report not found"
            exit 1
          fi
          if [ ! -f "results/fastqc/sample1_fastqc.zip" ]; then
            echo "FastQC ZIP report not found"
            exit 1
          fi
          echo "FastQC process test passed successfully"
      
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: fastqc-results
          path: results/fastqc/